### PR TITLE
added 5 codechef problems

### PR DESCRIPTION
**Pull request by aswinzz**

### CODE REVIEW

**Review by gauthamzz — APPROVED** [review]

**Review by gauthamzz — APPROVED** [review]

**Comment by faheemzunjani** [comment]
@ashwinzz Please include the links to your submissions so that I can verify if they are AC and if theyr are your submissions. Refer to previous PRs of @Anupam-dagar for help.

**Comment by aswinzz** [comment]
https://www.codechef.com/viewsolution/12826627  -Vcake
https://www.codechef.com/viewsolution/12826058  -TECH04
https://www.codechef.com/viewsolution/12826154    -MAXCNT
https://www.codechef.com/viewsolution/12826213  -packaging cupcake
https://www.codechef.com/viewsolution/12826221  -ATM
https://www.codechef.com/viewsolution/12826230  -SMLFACT
https://www.codechef.com/viewsolution/12826555  -FLIPCOIN
https://www.codechef.com/viewsolution/12826580  -SUMTRIAN
https://www.codechef.com/viewsolution/12826688  -KTTABLE
https://www.codechef.com/viewsolution/12827107  -RVRSPOLISH

**Comment by faheemzunjani** [comment]
@ashwinzz Please attach links of the form "https://www.codechef.com/viewsolution/12826154 " and not "https://www.codechef.com/submit/complete/12826213" because the second type of links are not accessible to external user. 
Thank you!

**Comment by aswinzz** [comment]
Done sir

**Comment by faheemzunjani** [comment]
@aswinzz Cross verified. Thank you! 
Merging now.

**Pull request merged**
