### PR TITLE
Added 10 codechef programs. 

### PR DESCRIPTION
**Pull request by Anupam-dagar**
This PR is for the issue no. #8

### CODE REVIEW

**Comment by gauthamzz** [comment]
How are we going to know which questions answers these are ? Faheem . I mean do you keep track of questions some where

**Review by gauthamzz — APPROVED** [review]

**Comment by faheemzunjani** [comment]
@gauthamzz In the issue I had mentioned to attach the link to the their submissions of these solutions to cross-verify that it's theirs and that they are correct. 
@Anupam-dagar please modify your pull request accordingly.

**Comment by Anupam-dagar** [comment]
Should I add the links here or in the code files as a comment?

**Comment by faheemzunjani** [comment]
Add them here only as a comment. Since, the files have their names as the questions' code so it's fine.

**Comment by Anupam-dagar** [comment]
1.CIELRCPT
https://www.codechef.com/viewsolution/12581775
2.FLOW001
https://www.codechef.com/viewsolution/12301367
3.FLOW006
https://www.codechef.com/viewsolution/12301404
4.REMISS
https://www.codechef.com/viewsolution/12301480
5.FLOW002
https://www.codechef.com/viewsolution/12301442
6.LUCKFOUR
https://www.codechef.com/viewsolution/12301556
7.START01
https://www.codechef.com/viewsolution/12301568
8.FLOW004
https://www.codechef.com/viewsolution/12301663
9.FSQRT
https://www.codechef.com/viewsolution/12301719
10.FLOW017
https://www.codechef.com/viewsolution/12301745

**Comment by faheemzunjani** [comment]
Everything checks out. Thank you! :) 
Merging.

**Pull request merged**
