### PR TITLE
added 35 hackerearth/codebuddy programs

### PR DESCRIPTION
**Pull request by aswinzz**

### CODE REVIEW

**Comment by aswinzz** [comment]
`
screenshot from 2017-02-15 03-24-37
screenshot from 2017-02-15 03-24-50
screenshot from 2017-02-15 03-25-07
screenshot from 2017-02-15 03-25-18
screenshot from 2017-02-15 03-25-30
screenshot from 2017-02-15 03-25-44
screenshot from 2017-02-15 03-25-56
screenshot from 2017-02-15 03-26-08
screenshot from 2017-02-15 03-26-19
screenshot from 2017-02-15 03-26-30
screenshot from 2017-02-15 03-26-42
screenshot from 2017-02-15 03-33-15
screenshot from 2017-02-15 03-35-01
screenshot from 2017-02-15 03-38-24
screenshot from 2017-02-15 03-39-12
screenshot from 2017-02-15 03-40-17
screenshot from 2017-02-15 03-40-30
screenshot from 2017-02-15 03-41-28
screenshot from 2017-02-15 03-42-55
screenshot from 2017-02-15 03-43-08
screenshot from 2017-02-15 03-44-21
screenshot from 2017-02-15 03-45-18
screenshot from 2017-02-15 03-45-27
screenshot from 2017-02-15 03-46-39
screenshot from 2017-02-15 03-46-48
screenshot from 2017-02-15 03-47-21
screenshot from 2017-02-15 03-53-31
screenshot from 2017-02-15 03-54-37
screenshot from 2017-02-15 03-55-35
screenshot from 2017-02-15 03-56-16
screenshot from 2017-02-15 03-56-56
screenshot from 2017-02-15 03-57-52
screenshot from 2017-02-15 04-07-18
screenshot from 2017-02-15 04-07-26
screenshot from 2017-02-15 04-07-33


































`

**Comment by aswinzz** [comment]
sir is this okay?

**Comment by aswinzz** [comment]
how much points should i count?

**Comment by faheemzunjani** [comment]
@aswinzz Count 20 points for every 10 programs added. Max number of PR by a user is 3 for this issue. So the max points you can earn for adding programs is 60. 

This PR looks good to me. Thank you! :)
Merging.

**Comment by gauthamzz** [comment]
@Anupam-dagar you added 120 points via adding programs please reduce it to 60

**Comment by Anupam-dagar** [comment]
I added 60 for codebuddy and 60 points for hackerearth as i committed before merging of my previous pull request. So two issues got fixed in 1 PR

**Comment by faheemzunjani** [comment]
I think 60points/platform is cool. @gauthamzz ?

**Comment by aswinzz** [comment]
So what point should i add?

**Comment by gauthamzz** [comment]
nah 60 total is fine :). For all platoforms, these you can get solutions from somewhere

**Pull request merged**
