### PR TITLE
Added 15 codebuddy programs and 15 hackerearth programs.

### PR DESCRIPTION
**Pull request by Anupam-dagar**
This PR is for the issue #16 

Added max no. of programs per user.
Counting 60 points towards it.

### CODE REVIEW

**Comment by Anupam-dagar** [comment]
Codebuddy doesn't allow eveyone to view solutions.
Will screenshots work for it?

**Comment by faheemzunjani** [comment]
@Anupam-dagar  Yep. Screenshots will do.

**Comment by faheemzunjani** [comment]
@Anupam-dagar  Also please make another directory for Codebuddy and add the corresponding codes there.

**Comment by Anupam-dagar** [comment]
Ok, I will add screenshots. 
Yes, I have added them in separate directory. 😀

**Comment by Anupam-dagar** [comment]
1.BDDYTT.cpp
screenshot from 2017-02-14 02-01-28
2.BUDDYNUM.cpp
screenshot from 2017-02-14 02-02-18
3.CHKVWL.c
screenshot from 2017-02-14 02-03-09
4.CUPCAKES.cpp
screenshot from 2017-02-14 02-03-51
5. DGTCHK.cpp
screenshot from 2017-02-14 02-04-49
6.FIBO1.cpp
screenshot from 2017-02-14 02-05-36
7.INTPALIN.cpp
screenshot from 2017-02-14 02-06-28
8.INVCNT1.cpp
screenshot from 2017-02-14 02-07-07
9.MAXNUM.cpp
screenshot from 2017-02-14 02-07-46
10.ODDEVE.c
screenshot from 2017-02-14 02-08-27
11.pattern1.cpp
screenshot from 2017-02-14 02-09-15
12.PRIME1.cpp
screenshot from 2017-02-14 02-09-58
13.RVRSRT.cpp
screenshot from 2017-02-14 02-10-32
14.SUM3.cpp
screenshot from 2017-02-14 02-11-21
15.TEJUCKWLK.c
screenshot from 2017-02-14 02-12-21

**Comment by Anupam-dagar** [comment]
Update:
Added 15 hackerearth programs.
Counting 60 points towards it.

**Comment by Anupam-dagar** [comment]
1.countdivisors.c
screenshot from 2017-02-14 02-30-02
2.factorial.c
screenshot from 2017-02-14 02-31-01
3.finaldestination.c
screenshot from 2017-02-14 02-32-14
4.findproduct.c
screenshot from 2017-02-14 02-32-59
5.goodstring.c
screenshot from 2017-02-14 02-33-46
6.greatkian.c
screenshot from 2017-02-14 02-34-27
7.life.c
screenshot from 2017-02-14 02-35-16
8.littlejhool.c
screenshot from 2017-02-14 02-36-07
9.min-max.c
screenshot from 2017-02-14 02-37-00
10.palindromicstring.c
screenshot from 2017-02-14 02-37-55
11.roydp.c
screenshot from 2017-02-14 02-38-50
12.stringsum.c
default
13.togglestring.c
screenshot from 2017-02-14 02-40-33
14.war.c
screenshot from 2017-02-14 02-41-24
15.monk.c
screenshot from 2017-02-14 02-42-46

**Comment by faheemzunjani** [comment]
Awesome job! Thank you! :D 
Merging.

**Pull request merged**
